### ISSUE TITLE
Geographic scope map incorrect for Amphibians of the Former USSR

### ISSUE THREAD

**Issue by thomasstjerne** [gbif/portal-feedback#1484]
The geographic scope map for this dataset page "Amphibians of the Former USSR" appears to be incorrect.

https://www.gbif.org/dataset/e1c320f6-370e-4d5e-8253-9b5285a0775f

It seems to be a content issue. The westBoundingCoordinate and eastBoundingCoordinate should be swapped in the EML:

`<westBoundingCoordinate>-178.717</westBoundingCoordinate>
          <eastBoundingCoordinate>19.95</eastBoundingCoordinate>`

**Comment by ManonGros** [comment]
It looks like the problem has been solved. Tell me if I am wrong.

**Comment by MortenHofft** [comment]
the problem is still there
<img width="762" alt="screen shot 2018-09-04 at 15 09 26" src="https://user-images.githubusercontent.com/6759267/45033346-8af73b80-b054-11e8-8465-c137edc8eff9.png">

**Comment by ManonGros** [comment]
The publishers have been notified by email.

**Comment by MortenHofft** [comment]
This is an issue with the IPT- it swappes coordinates to indicate dateline crossing. This is not the convention used by most libraries.

**Comment by jhnwllr** [comment]
I am writing to the publishers again.
