### ISSUE TITLE
Polochic Valley is in Guatemala and not in India

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2305]
**Polochic Valley is in Guatemala and not in India**

Location of this record Polochic Valley is in Guatemala and not in India

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d5dfbd4e93c3a262b99a1f413ef4db57:0d7cdfe0a087d58d7a6c0781cff5ced23dc9e68c9aaa054e85169f3902f34e204e7ca21a5c83458d240867c7429a7e7da7d54f52cccf7a4c055aaa2853c2d4a4)
System: Chrome 78.0.3904 / Windows 8.1.0.0
Referer: https://www.gbif.org/occurrence/1224735998
Window size: width 1680 - height 858
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-21T15:04:13.765Z',mode:absolute,to:'2019-11-21T15:10:13.765Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-11-21T15:04:13.765Z',mode:absolute,to:'2019-11-21T15:10:13.765Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 7b468209-8d5c-477b-b118-cdf04dde9912
publishingOrgKey: c5f7ef70-e233-11d9-a4d6-b8a03c50a862

**Comment by ManonGros** [comment]
Publisher contacted by email.

**Comment by ManonGros** [comment]
The data has been corrected at the source.

**Comment by jhnwllr** [comment]
record still shows India and not Guatemala
![image](https://github.com/gbif/portal-feedback/assets/4245213/84357b68-6d78-458d-80d4-d9b44e06a26d)
